#!/usr/bin/env python3
"""
RAG Integration Test Script (Pure API Version)

Tests the complete RAG (Retrieval-Augmented Generation) workflow:
1. Load saved JWT token (generated by generate_test_token.py)
2. Upload a document with machine learning content
3. Verify document is indexed in RAG system
4. Ask questions about the uploaded document
5. Verify RAG retrieval returns relevant context
6. Check if LLM response includes information from the document

Usage:
    # First time: Generate token (in bread environment)
    conda activate bread
    python test/generate_test_token.py
    
    # Then run tests (in any Python environment)
    python test/test_rag_integration.py

Note: This test uses only API calls, no backend imports needed.
      Token is valid for 5 hours after generation.
"""
import requests
import json
import time
import os
from io import BytesIO

# Configuration
BASE_URL = "http://localhost:8203/api"
RAG_URL = "http://localhost:8602"

def load_saved_token():
    """Load JWT token from file (generated by generate_test_token.py)"""
    print("\n[1] Loading authentication token...")
    
    token_file = os.path.join(os.path.dirname(__file__), '.test_token')
    
    if not os.path.exists(token_file):
        print(f"❌ Token file not found: {token_file}")
        print()
        print("📝 First-time setup required:")
        print("   1. conda activate bread")
        print("   2. python test/generate_test_token.py")
        print()
        print("   This will create test user and save a token valid for 5 hours")
        print("   Then you can run this test in any Python environment")
        print()
        return None, None
    
    try:
        with open(token_file, 'r') as f:
            lines = f.readlines()
            token = lines[0].strip()
            user_id = int(lines[1].strip()) if len(lines) > 1 else None
        
        print(f"✅ Token loaded from file")
        print(f"   User ID: {user_id}")
        print(f"   Token: {token[:30]}...")
        
        return token, user_id
        
    except Exception as e:
        print(f"❌ Error reading token file: {e}")
        print()
        print("Please regenerate token:")
        print("   conda activate bread")
        print("   python test/generate_test_token.py")
        print()
        return None, None

def test_rag_integration():
    """Test complete RAG integration flow"""
    print("=" * 70)
    print("Testing RAG Integration with File Upload and Chat")
    print("=" * 70)
    
    # Step 1: Load saved token
    token, user_id = load_saved_token()
    
    if not token:
        print("❌ Cannot proceed without token")
        return
    
    headers = {"Authorization": f"Bearer {token}"}
    
    # Step 2: Create a test PDF with some content
    print("\n[2] Creating test PDF content...")
    test_content = """Machine Learning Tutorial
    
    What is Machine Learning?
    Machine learning is a subset of artificial intelligence that enables systems to learn and improve from experience without being explicitly programmed.
    
    Types of Machine Learning:
    1. Supervised Learning - Learning from labeled data
    2. Unsupervised Learning - Finding patterns in unlabeled data
    3. Reinforcement Learning - Learning through trial and error
    
    Key Concepts:
    - Training Data: The dataset used to train the model
    - Features: Input variables used to make predictions
    - Labels: Output variables we want to predict
    - Model: The mathematical representation learned from data
    """
    
    test_file = BytesIO(test_content.encode('utf-8'))
    test_file.name = "ml_tutorial.txt"
    
    # Step 3: Upload file
    print("\n[3] Uploading file to backend...")
    files = {'file': ('ml_tutorial.txt', test_file, 'text/plain')}
    data = {'session_id': ''}
    
    upload_response = requests.post(
        f"{BASE_URL}/chat/upload",
        headers=headers,
        files=files,
        data=data
    )
    
    print(f"Status Code: {upload_response.status_code}")
    upload_data = upload_response.json()
    print(f"Response: {json.dumps(upload_data, indent=2)}")
    
    if upload_response.status_code != 200:
        print(f"❌ File upload failed!")
        return
    
    print(f"✅ File uploaded successfully!")
    
    if upload_data.get("rag_indexed"):
        print(f"✅ Document indexed in RAG!")
    else:
        print(f"⚠️  RAG indexing status: {upload_data.get('rag_error', 'Unknown')}")
    
    session_id = upload_data.get("session_id")
    
    # Step 4: Wait a moment for indexing
    print("\n[4] Waiting for RAG indexing...")
    import time
    time.sleep(2)
    
    # Step 5: Ask a question about the uploaded document
    print("\n[5] Asking question about uploaded content...")
    question = "What are the three types of machine learning?"
    
    print(f"Question: {question}")
    print("Streaming response:")
    print("-" * 70)
    
    response = requests.post(
        f"{BASE_URL}/chat/stream",
        headers=headers,
        data={
            "message": question,
            "session_id": session_id
        },
        stream=True
    )
    
    full_response = ""
    for line in response.iter_lines():
        if line:
            line_str = line.decode('utf-8')
            if line_str.startswith('data: '):
                try:
                    data = json.loads(line_str[6:])
                    if 'chunk' in data:
                        chunk = data['chunk']
                        print(chunk, end='', flush=True)
                        full_response += chunk
                except json.JSONDecodeError:
                    pass
    
    print("\n" + "-" * 70)
    
    # Step 6: Test RAG retrieval directly
    print("\n[6] Testing direct RAG retrieval...")
    
    if user_id:
        rag_response = requests.post(
            f"{RAG_URL}/retriever",
            json={
                "question": question,
                "user_id": str(user_id),
                "personal_k": 3,
                "public_k": 2,
                "final_k": 5
            }
        )
        
        if rag_response.status_code == 200:
            rag_data = rag_response.json()
            hits = rag_data.get('hits', [])
            print(f"✅ RAG returned {len(hits)} results:")
            for i, hit in enumerate(hits[:3], 1):
                print(f"\n  {i}. {hit.get('text', '')[:100]}...")
        else:
            print(f"❌ RAG retrieval failed: {rag_response.status_code}")
    else:
        print("❌ No user_id available for RAG retrieval test")
    
    print("\n" + "=" * 70)
    print("Test completed!")
    print("=" * 70)
    
    # Summary
    print("\n📊 Summary:")
    print(f"  - File upload: {'✅' if upload_response.status_code == 200 else '❌'}")
    print(f"  - RAG indexing: {'✅' if upload_data.get('rag_indexed') else '⚠️'}")
    print(f"  - Chat response: {'✅' if full_response else '❌'}")
    print(f"  - Response contains context: {'✅' if 'supervised' in full_response.lower() or 'unsupervised' in full_response.lower() else '❓'}")

if __name__ == "__main__":
    test_rag_integration()
